### PR TITLE
Move Sing up Activity to login Activity

### PR DESCRIPTION
**Pull request by darsh8114**
# Pull Request 

## Proposed Changes
- Give a summary of the changes made in the repository. 
- List the dependencies used. 
- Also mention the issue number [Fixes #(issue)].

## Types of changes made
- [ ] Fixed Bug
- [ ] Added new Features
- [ ] Edited Documentations
- [x] Enhanced the working of code
- [x] Additional Changes
- *Mention any Additional Change here*

## Additional Info
Provide additional information(*if any*) you want to convey.

## Viability of Code
Describe the tests that you ran to verify the changes made. Mention the tests for easy reproducibility.
- Test 1
- Test 2

#### Mention(*if any*) specific Test Configurations used:
- Filmware version:
- Hardware: 
- Toolchain: 
- SDK: 

## Screenshots or GIFs (*if any*)
Attach screenshots of the changes made for easy reference.
Original | Updated
:-----:|:-----:
*Attach_Original_Screenshot* | *Attach_Updated_Screenshot*

## Checklist:
- [ ] My code follows the Mentioned Guidelines for the project
- [ ] I have self-reviewed the changes made
- [ ] I have made the changes easy to understand by adding comments
- [ ] My changes does not generate new warnings/errors
- [ ] I have attached relevant screenshots to display the changes made
- [ ] I have made the required changes to the documentations

### CODE REVIEW

**Comment by darsh8114** [comment]
I have made changes as mentioned. If you find any issue then let me know I will fix it

**Comment by siddhantdrk** [comment]
@darsh8114  please try to link the respective issue with your further PR's

**Review by siddhantdrk — CHANGES_REQUESTED** [review]
Please make the TextView variable  as private

**Comment by darsh8114** [comment]
I have made the change as you said

**Review by siddhantdrk — APPROVED** [review]

**Pull request merged**
